name: test

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # os: [ubuntu-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: macos dependencies
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew cask install firefox    
    - name: npm install, and npm test
      run: |
        npm ci
        npm test
      env:
        CI: true
        OS: ${{ matrix.os }}